### ISSUE TITLE
Comment box for root file

### ISSUE THREAD

**Issue by xmatter** [zach-hartwig/ADAQAcquisition#1]
For future versions, please add a comment box to save experimental parameters to the root file.

**Comment by zach-hartwig** [comment]
I am working on this feature presently. Seems relatively straightforward. There will be a TGTextButton to click that will open a TGTextEdit in a separate window. You should be able to write sentences, paragraphs, etc. This will be stored in the ADAQ file (most likely in a TString) to be read out via ROOT or ADAQAnalysis. I expect this feature to be released with official 1.0.0 version.

**Comment by zach-hartwig** [comment]
This feature is now implemented in the HEAD of the master branch.

A text button titled "Comment" has been added to the "Waveform storage" section of the "Persistent storage" subtab under the main display canvas. To activate the button, you must start acquiring data and create an ADAQ file. 

By clicking the "Comment" button, a large text editor in a new window will appear enabling you to add paragraph-length comments. Clicking save (or typing ctrl-s) will save the comments. Clicking the "Close" button to write the ADAQ file will save the comments to the ADAQ file as a TObjString object named "FileComment". Note that before you click the "Close" button to write the ADAQ file, clicking the "Comments" button again will load any previously existing comments you made for this file so that you can edit or add additional information throughout the data run without deleting previous comments.

Please let me know if you have issues with this new feature. I will be closing this issue.
