### ISSUE TITLE
Optical Links

### ISSUE THREAD

**Issue by xmatter** [zach-hartwig/ADAQAcquisition#2]
Does the ADAQAcquisition have support for optical links such as the A3818?

**Comment by zach-hartwig** [comment]
In short, no. This is because I do not have this hardware to develop on. However, it should be a very straightforward addition provides that the VME access methods are identical whether using V1718 (USB) or A3818 (Fiber). The code was designed with modular updates like this in mind so it's just a matter of me having the hardware to do the software development. If this is something you can provide access to, I will consider adding the capabilities.

**Comment by zach-hartwig** [comment]
I am hoping that I will be able to acquire some new CAEN hardware for development soon; however, unless hardware is loaned to me for specific development purposes, there is nothing that I can do to address optical readout for the A3818 hardware. Thanks for the feeback, please check back in the future if this is a pressing need for your application.
