### ISSUE TITLE
Saving data with calibration

### ISSUE THREAD

**Issue by lkesler** [zach-hartwig/ADAQAcquisition#28]
Zach,

It looks like ADAQ is saving the data with the calibration, i.e. when I save data with the spectrum calibrated, it's saved with the calibration, not with the original ADC values. It did this before and you fixed the issue, so I'm not sure how it's started again. We can troubleshoot sometime if you'd like.

I'm running version 1.6.4,DPP-PSD, running in List only mode, saving energy only.

**Comment by zach-hartwig** [comment]
This issue was fixed in version 1.6.6 (See the [Changelog](https://github.com/zach-hartwig/ADAQAcquisition/blob/master/Changelog.md) for details. The most recent version is 1.6.10, which fixes a number of other important issues compared to 1.6.4. Please upgrade.

Reopen this issue if you continue to have problems.
