### ISSUE TITLE
PSD information not saving while in nonupdateable

### ISSUE THREAD

**Issue by xmatter** [zach-hartwig/ADAQAcquisition#7]
While in nonupdateable, control-style ttl, and using a timer, the PSD information is not saved.  It will save with a continuous graphical display with the same control-style and timer.

**Comment by zach-hartwig** [comment]
Hello,

Thanks for reporting this. The issue you raise could be considered either a "bug" or a "feature". When you click "Nonupdateable mode", the idea is to maximize the efficiency of ADAQAcquisition to acquire and store data. At present, this means that (a) waveforms are *not* analyzed pulse height, pulse area, PSD integrals, etc, and that (b) graphical objects are *not* produced. The only action taken is to readout the full waveforms from the digitizer FPGA buffer to the PC buffer and then (optionally) save the full waveform directly to the ADAQ file. Because waveforms are *not* processed (see (a) above), it is not possible to save waveform data (pulse height/area, PSD integrals) to the ADAQ files. If you only want processed data, this is a "bug"'; however, if you want to maximize acquisition/storage of full waveforms, this is a "feature" since time is not wasted analyzing waveforms.

If you are not placing extreme demands on the data rate, I would suggest running in "Updateable mode" and setting the "Events before readout" number to 30 to 50. This will provide a very high acquisition rate and allow you to save only processed data to file (and optionally to *not* save the full waveforms if you do not want them).

Let me know if this meets your application. It might be possible to implement for granular control of what is saved and how efficienct the processing is done.
